version: "3.9"

services:
  frontend:
    build: ./frontend
    restart: always
    networks:
      - appnet

  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "10000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge